/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.ventanas;

import edu.cuc.palabras.LongitudIncorrectaException;
import edu.cuc.palabras.LongitudSinonimoIncorrectaException;
import edu.cuc.palabras.Palabra;
import edu.cuc.palabras.PalabraRepetidaException;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;           

/**
 *
 * @author alexisdelahoz
 */
public class FrmPalabras extends javax.swing.JFrame {

    private Palabra palabraNueva;

    /**
     * Creates new form FrmPalabras
     */
    public FrmPalabras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSinonimo = new javax.swing.JTextField();
        cmdIngresarSinonimo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        cmdCantidad = new javax.swing.JButton();
        cmdPromedioLongitud = new javax.swing.JButton();
        cmdMayorLongitud = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        cmdIngresarPalabra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPalabra1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnMaxLongitud = new javax.swing.JSpinner();
        cmdIngresarPalabra1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSinonimos = new javax.swing.JList<String>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Primer Diccionario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Sinónimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Ingrese sinónimo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 31, -1, 20));

        txtSinonimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSinonimo.setOpaque(false);
        txtSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSinonimoActionPerformed(evt);
            }
        });
        txtSinonimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSinonimoKeyTyped(evt);
            }
        });
        jPanel2.add(txtSinonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 140, -1));

        cmdIngresarSinonimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdIngresarSinonimo.setForeground(new java.awt.Color(255, 153, 0));
        cmdIngresarSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490739089_Open.png"))); // NOI18N
        cmdIngresarSinonimo.setBorderPainted(false);
        cmdIngresarSinonimo.setContentAreaFilled(false);
        cmdIngresarSinonimo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdIngresarSinonimoMouseMoved(evt);
            }
        });
        cmdIngresarSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarSinonimoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresarSinonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 460, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galeria De Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        cmdCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/cantidad32x32.png"))); // NOI18N
        cmdCantidad.setBorderPainted(false);
        cmdCantidad.setContentAreaFilled(false);
        cmdCantidad.setFocusable(false);
        cmdCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdCantidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdCantidad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdCantidadMouseMoved(evt);
            }
        });
        cmdCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidadActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdCantidad);

        cmdPromedioLongitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/promedio32x32.png"))); // NOI18N
        cmdPromedioLongitud.setBorderPainted(false);
        cmdPromedioLongitud.setContentAreaFilled(false);
        cmdPromedioLongitud.setFocusable(false);
        cmdPromedioLongitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdPromedioLongitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdPromedioLongitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdPromedioLongitudMouseMoved(evt);
            }
        });
        cmdPromedioLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPromedioLongitudActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdPromedioLongitud);

        cmdMayorLongitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/mayorque.png"))); // NOI18N
        cmdMayorLongitud.setBorderPainted(false);
        cmdMayorLongitud.setContentAreaFilled(false);
        cmdMayorLongitud.setFocusable(false);
        cmdMayorLongitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdMayorLongitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdMayorLongitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdMayorLongitudMouseMoved(evt);
            }
        });
        cmdMayorLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorLongitudActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdMayorLongitud);

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490660116_icons_delete.png"))); // NOI18N
        cmdEliminar.setBorderPainted(false);
        cmdEliminar.setContentAreaFilled(false);
        cmdEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdEliminarMouseMoved(evt);
            }
        });
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdEliminar);

        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490660209_Log Out.png"))); // NOI18N
        cmdSalir.setBorderPainted(false);
        cmdSalir.setContentAreaFilled(false);
        cmdSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdSalirMouseMoved(evt);
            }
        });
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdSalir);

        jPanel3.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 52));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 230, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Palabra Nueva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Ingrese palabra: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 21, -1, 40));

        txtPalabra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPalabra.setOpaque(false);
        txtPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabraActionPerformed(evt);
            }
        });
        txtPalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 171, -1));

        cmdIngresarPalabra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdIngresarPalabra.setForeground(new java.awt.Color(255, 153, 0));
        cmdIngresarPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490739089_Open.png"))); // NOI18N
        cmdIngresarPalabra.setToolTipText("");
        cmdIngresarPalabra.setBorderPainted(false);
        cmdIngresarPalabra.setContentAreaFilled(false);
        cmdIngresarPalabra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdIngresarPalabraMouseMoved(evt);
            }
        });
        cmdIngresarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIngresarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 440, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Palabra con limite de tamaño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Ingrese palabra: ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 31, -1, -1));

        txtPalabra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPalabra1.setOpaque(false);
        txtPalabra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabra1KeyTyped(evt);
            }
        });
        jPanel4.add(txtPalabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 171, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Maxima Longitud Sinónimo: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        spnMaxLongitud.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jPanel4.add(spnMaxLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        cmdIngresarPalabra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdIngresarPalabra1.setForeground(new java.awt.Color(255, 153, 0));
        cmdIngresarPalabra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490739089_Open.png"))); // NOI18N
        cmdIngresarPalabra1.setToolTipText("");
        cmdIngresarPalabra1.setBorderPainted(false);
        cmdIngresarPalabra1.setContentAreaFilled(false);
        cmdIngresarPalabra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdIngresarPalabra1MouseMoved(evt);
            }
        });
        cmdIngresarPalabra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarPalabra1ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdIngresarPalabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 20, 80, 40));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 440, 100));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 230));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 153, 0));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstSinonimos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstSinonimos.setOpaque(false);
        jScrollPane1.setViewportView(lstSinonimos);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 190));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 230, 230));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/american-flag-wallpapers_6121_1440x900.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarPalabraActionPerformed
        if (txtPalabra.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese Palabra", "Error", JOptionPane.ERROR_MESSAGE);
            txtPalabra.requestFocusInWindow();
        } else {
            introducirPalabra();
        }
    }//GEN-LAST:event_cmdIngresarPalabraActionPerformed

    private void txtPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabraActionPerformed
        introducirPalabra();
    }//GEN-LAST:event_txtPalabraActionPerformed

    private void cmdIngresarSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarSinonimoActionPerformed
        if(txtSinonimo.getText().trim().isEmpty()){ 
          JOptionPane.showMessageDialog(this,"Adiccione Sinonimo","Error",JOptionPane.ERROR_MESSAGE); 
          txtSinonimo.requestFocusInWindow();
        }else{
        try {
            palabraNueva.adicionarConLongitud(new Palabra(txtSinonimo.getText()));
            txtSinonimo.setText(null);
            JOptionPane.showMessageDialog(this,
                    "Sinonimo ingresado!",
                    "Confirmación",
                    JOptionPane.INFORMATION_MESSAGE);
            //Actualizar Lista Sinonimos
            DefaultListModel<String> listado = palabraNueva.getListSinonimos();
            lstSinonimos.setModel(listado);
        } catch (LongitudIncorrectaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LongitudSinonimoIncorrectaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }  
    }//GEN-LAST:event_cmdIngresarSinonimoActionPerformed

    private void txtSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSinonimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSinonimoActionPerformed

    private void cmdCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidadActionPerformed
        JOptionPane.showMessageDialog(this,
                "La cantidad de sinonimos es: " + palabraNueva.cantidadSinonimos(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdCantidadActionPerformed

    private void cmdPromedioLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPromedioLongitudActionPerformed
        JOptionPane.showMessageDialog(this,
                "El promedio por longitud es: " + palabraNueva.promedioLongitud(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdPromedioLongitudActionPerformed

    private void cmdMayorLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorLongitudActionPerformed
        JOptionPane.showMessageDialog(this,
                "El sinonimo de mayor longitud es: " + palabraNueva.sinonimoMayorLongitud(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdMayorLongitudActionPerformed

    private void cmdIngresarPalabra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarPalabra1ActionPerformed
        if(txtPalabra1.getText().trim().isEmpty()){ 
          JOptionPane.showMessageDialog(rootPane,"Limite Palabra","Error",JOptionPane.ERROR_MESSAGE); 
          txtPalabra1.requestFocusInWindow();
        }else{
        try {
            // Ingresar palabra con longitud de sinonimos
            String texto = txtPalabra1.getText();
            int maxLongitud = (int) spnMaxLongitud.getValue();
            palabraNueva = new Palabra(texto, maxLongitud);
            txtPalabra1.setText(null);
            JOptionPane.showMessageDialog(this,
                    "Palabra ingresada!",
                    "Confirmación",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (LongitudIncorrectaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LongitudSinonimoIncorrectaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }   
    }//GEN-LAST:event_cmdIngresarPalabra1ActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        //Veerificar la seleccion de la lista
        String elementoSeleccionado = lstSinonimos.getSelectedValue();
        if (elementoSeleccionado != null) {
            try {
                Palabra sinonimoAEliminar = new Palabra(elementoSeleccionado);
                palabraNueva.eliminarSinonimo(sinonimoAEliminar);
                //Actualizar Lista Sinonimos
                DefaultListModel<String> listado = palabraNueva.getListSinonimos();
                lstSinonimos.setModel(listado);
            } catch (LongitudIncorrectaException ex) {
                Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un sinónimo");
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
       if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?", "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){ 
                       System.exit(0);     
                     }    
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void txtPalabraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabraKeyTyped
     
         char c = evt.getKeyChar();

        if (!Character.isLetter(c)) {
            getToolkit();
            evt.consume();
        }
      JOptionPane.showMessageDialog(this,"Solo se pueden ingresar letras");  
    }//GEN-LAST:event_txtPalabraKeyTyped

    private void txtPalabra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabra1KeyTyped
       
         char c = evt.getKeyChar();

        if (!Character.isLetter(c)) {
            getToolkit();
            evt.consume();
        }
      JOptionPane.showMessageDialog(this,"Solo se pueden ingresar letras");   
        
    }//GEN-LAST:event_txtPalabra1KeyTyped

    private void txtSinonimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSinonimoKeyTyped
        
         char c = evt.getKeyChar();

        if (!Character.isLetter(c)) {
            getToolkit();
            evt.consume();
        }
      JOptionPane.showMessageDialog(this,"Solo se pueden ingresar letras");   
    }//GEN-LAST:event_txtSinonimoKeyTyped

    private void cmdIngresarPalabraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdIngresarPalabraMouseMoved
        
        String Ingresar_Palabra = "Boton Ingresar Palabra"; 
        cmdIngresarPalabra.setToolTipText(Ingresar_Palabra);  
    }//GEN-LAST:event_cmdIngresarPalabraMouseMoved

    private void cmdIngresarPalabra1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdIngresarPalabra1MouseMoved
        
        String Limite_Palabra = "Boton Limite Palabra"; 
        cmdIngresarPalabra1.setToolTipText(Limite_Palabra);  
    }//GEN-LAST:event_cmdIngresarPalabra1MouseMoved

    private void cmdIngresarSinonimoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdIngresarSinonimoMouseMoved
        
        String Adiccione_Sinonimo = "Boton Ingresar Sinonimo"; 
        cmdIngresarSinonimo.setToolTipText(Adiccione_Sinonimo);  
    }//GEN-LAST:event_cmdIngresarSinonimoMouseMoved

    private void cmdCantidadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCantidadMouseMoved
        
        String Cantidad = "Boton Cantidad Sinonimos"; 
        cmdCantidad.setToolTipText(Cantidad);  
    }//GEN-LAST:event_cmdCantidadMouseMoved

    private void cmdPromedioLongitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPromedioLongitudMouseMoved
        
        String Promedio = "Boton Promedio Longitud"; 
        cmdPromedioLongitud.setToolTipText(Promedio);  
    }//GEN-LAST:event_cmdPromedioLongitudMouseMoved

    private void cmdMayorLongitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMayorLongitudMouseMoved
        
        String Mayor = "Boton Mayor Longitud"; 
        cmdMayorLongitud.setToolTipText(Mayor);  
    }//GEN-LAST:event_cmdMayorLongitudMouseMoved

    private void cmdEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdEliminarMouseMoved
        
        String Eliminar = "Boton Eliminar Sinonimo"; 
        cmdEliminar.setToolTipText(Eliminar);  
    }//GEN-LAST:event_cmdEliminarMouseMoved

    private void cmdSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSalirMouseMoved
        
        String Salir = "Boton Salir"; 
        cmdSalir.setToolTipText(Salir);       
    }//GEN-LAST:event_cmdSalirMouseMoved

    private void introducirPalabra() throws HeadlessException {
        try {
            palabraNueva = new Palabra(txtPalabra.getText());
            //Limpiar la caja
            txtPalabra.setText(null);
            JOptionPane.showMessageDialog(this,
                    "Palabra ingresada!",
                    "Confirmación",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (LongitudIncorrectaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPalabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCantidad;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdIngresarPalabra;
    private javax.swing.JButton cmdIngresarPalabra1;
    private javax.swing.JButton cmdIngresarSinonimo;
    private javax.swing.JButton cmdMayorLongitud;
    private javax.swing.JButton cmdPromedioLongitud;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> lstSinonimos;
    private javax.swing.JSpinner spnMaxLongitud;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtPalabra1;
    private javax.swing.JTextField txtSinonimo;
    // End of variables declaration//GEN-END:variables
}
